version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  publish:
    docker:
      - image: react
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build and publish Docker image
          command: |
            docker build -t my-docker-image:latest .
            docker tag my-docker-image:latest wilsonlimdocker90/education-space:latest
            docker push wilsonlimdocker90/education-space:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - publish
