version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  test:
    docker:
      - image: wilsonlimdocker90/education-space
    steps:
      - checkout
      # Add your test steps here
      - run: echo "Running tests..."

  publish:
    docker:
      - image: wilsonlimdocker90/education-space
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build and publish Docker image
          command: |
            docker build -t my-docker-image:latest .
            docker tag my-docker-image:latest $DOCKERHUB_USERNAME/my-docker-image:latest
            docker push $DOCKERHUB_USERNAME/my-docker-image:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
